# Generated by Django 5.0.6 on 2024-07-02 23:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_dailylogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyLogs',
            new_name='DailyLogin',
        ),
    ]
